/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/ui/button/Button.vue')['default']
    Card: typeof import('./src/components/ui/card/Card.vue')['default']
    CardContent: typeof import('./src/components/ui/card/CardContent.vue')['default']
    CardDescription: typeof import('./src/components/ui/card/CardDescription.vue')['default']
    CardFooter: typeof import('./src/components/ui/card/CardFooter.vue')['default']
    CardHeader: typeof import('./src/components/ui/card/CardHeader.vue')['default']
    CardTitle: typeof import('./src/components/ui/card/CardTitle.vue')['default']
    Checkbox: typeof import('./src/components/ui/checkbox/Checkbox.vue')['default']
    FormControl: typeof import('./src/components/ui/form/FormControl.vue')['default']
    FormDescription: typeof import('./src/components/ui/form/FormDescription.vue')['default']
    FormField: typeof import('vee-validate')['Field']
    FormItem: typeof import('./src/components/ui/form/FormItem.vue')['default']
    FormLabel: typeof import('./src/components/ui/form/FormLabel.vue')['default']
    FormMessage: typeof import('./src/components/ui/form/FormMessage.vue')['default']
    Input: typeof import('./src/components/ui/input/Input.vue')['default']
    Label: typeof import('./src/components/ui/label/Label.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WithLabel: typeof import('./src/components/WithLabel.vue')['default']
  }
}
